url: "https://simaqie.github.io"

# Basic Information 
title: Qie Sima
# subtitle:
position: Graduate Research Assistant
# subposition:
# subposition_link:
affiliation: Tsinghua University
subaffiliation: Department of Computer Science 
affiliation_link: https://www.tsinghua.edu.cn
subaffiliation_link: https://www.cs.tsinghua.edu.cn/csen/
email: simaqie@gmail.com
address: 30 Shuangqing Rd, Beijing, CHINA 100084
address_link: https://goo.gl/maps/aQZfmiKjQmqbDsVY9



# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Embodied Intelligence, Robotic Manipulation, Multimodal Learning, Tsinghua University
description: Qie Sima - Graduate Research Assistant at Tsinghua University, working on Embodied Intelligence, Robotic Manipulation and Multimodal Learning.
canonical: https://simaqie.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=SswIhvMAAAAJ&hl=zh-CN
cv_link: assets/files/QieSima_CV.pdf
github_link: https://github.com/SimaQie
linkedin:  https://www.linkedin.com/in/qie-s-64251b170
# twitter:

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/QieSima.png
# logo: ./assets/img/logo.png
favicon: ./assets/img/Tsinghua.png
favicon_dark: ./assets/img/Tsinghua.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false


# Visitor Map & Counter
mapmyvisitors:
  id: "KqkOMqVSp5x0Vqv2ZTmK94SNoil6m-bQ_CfMAUdWeho" # latest ID from MapMyVisitors dashboard

visitor_counter:
  enable: true  # Toggle visitor counter badge in footer
  path: ""      # Optional: custom path for counting, defaults to site.url



# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# Blog posts
permalink: /blog/:year/:month/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - .zcode
